### ISSUE TITLE
IDEA cannot open xml error

### ISSUE THREAD

**Issue by Swiftlyfisher** [shlaikov/intellij-bpmn2-plugin#24]
IDEA 2023.3.2

java.lang.Throwable: Assertion failed: Already disposed
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:469)
	at com.intellij.util.Alarm.checkDisposed(Alarm.java:67)
	at com.intellij.util.Alarm._addRequest(Alarm.java:212)
	at com.intellij.util.Alarm.addRequest(Alarm.java:176)
	at com.github.shlaikov.intellijbpmn2plugin.utils.LoadableJCEFHtmlPanel$2.onLoadStart(LoadableJCEFHtmlPanel.kt:83)
	at com.intellij.ui.jcef.JBCefClient$11.lambda$onLoadStart$1(JBCefClient.java:539)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.lambda$handle$1(JBCefClient.java:744)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.handle(JBCefClient.java:744)
	at com.intellij.ui.jcef.JBCefClient$11.onLoadStart(JBCefClient.java:538)
	at jcef/org.cef.CefClient.onLoadStart(CefClient.java:730)

**Comment by shlaikov** [comment]
Hello @Swiftlyfisher! Sorry for the long answer. At first glance, this function faults when throw error by timeout. How much does the `.bpmn` file size?

**Comment by shlaikov** [comment]
@Swiftlyfisher I need more input. Can't reproduce.

**Comment by Ugolnikof** [comment]
I have the same problem
IntelliJ IDEA 2023.2.6 (Community Edition)
`java.lang.Throwable: Assertion failed: Already disposed
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:465)
	at com.intellij.util.Alarm.checkDisposed(Alarm.java:69)
	at com.intellij.util.Alarm._addRequest(Alarm.java:214)
	at com.intellij.util.Alarm.addRequest(Alarm.java:178)
	at com.github.shlaikov.intellijbpmn2plugin.utils.LoadableJCEFHtmlPanel$2.onLoadStart(LoadableJCEFHtmlPanel.kt:83)
	at com.intellij.ui.jcef.JBCefClient$11.lambda$onLoadStart$1(JBCefClient.java:543)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.lambda$handle$1(JBCefClient.java:730)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.handle(JBCefClient.java:730)
	at com.intellij.ui.jcef.JBCefClient$11.onLoadStart(JBCefClient.java:542)
	at jcef/org.cef.CefClient.onLoadStart(CefClient.java:730)
`

**Comment by Ugolnikof** [comment]
The .bpmn file is not more than 30 Kb

**Comment by shlaikov** [comment]
Hello @Ugolnikof! I tried to reproduce it on the same version, but nothing. What OS are you using?
![Screenshot 2024-04-23 at 11 30 15](https://github.com/shlaikov/intellij-bpmn2-plugin/assets/16617640/8e9fa30d-f0c3-44ce-800b-1dea28f72ff4)

**Comment by McBlankenburg** [comment]
I have problem too and i can give you my .bpmn
https://github.com/Progress-House/ofitoo-doc/blob/official/business-analysis/bpmn-2.0/create-user-account-by-email.bpmn

when i deleted few elements it started working. 
I think the file can't be loaded into a string, which seems strange to me because I didn't know that a string had any character limits.

**Comment by shlaikov** [comment]
@McBlankenburg Thanks for the file provided. I realized that the reason was to convert CharSequence to String, everything will work in the next release!

@Ugolnikof @Swiftlyfisher After checking the patch, please put a yellow star☺️. Thanks again!

**Comment by Ugolnikof** [comment]
@shlaikov When will be the next release?

**Comment by McBlankenburg** [comment]
@shlaikov it saves my busy ass. I had to convert it to .svg so I had 2x more files in directory. Thanks you very much :)

**Comment by Ugolnikof** [comment]
@shlaikov Thanks a lot! When can I try it?

**Comment by shlaikov** [comment]
@Ugolnikof JetBrains is reviewing this update. They say it will be approved within two business days of uploading.
Plugin was sent for moderation on June 9th.

**Comment by Ugolnikof** [comment]
@shlaikov Thanks! Today I tried the updated version of the plugin, but when I open the file I get a black screen.... I tried Community v2023.2.6 and Ultimate v2024.1
![image](https://github.com/shlaikov/intellij-bpmn2-plugin/assets/122048993/ea81c1d6-11e1-4009-92b7-159ff898f0c6)

**Comment by Piratux** [comment]
Hello, any progress on this?

I get the same black screen when trying to check diagram of `.bpmn` file.

**Comment by shlaikov** [comment]
Hi @Swiftlyfisher @Ugolnikof @McBlankenburg @Piratux 👋

Fix landed on `main`. Root cause was a broken `removeCDATA` regex in `WebView.kt` that mangled XML before passing it to bpmn-js — the modern bpmn-js parser handles CDATA natively, so the stripper was both unnecessary and harmful.

What's in **v1.1.0**:
- CDATA in BPMN diagrams renders correctly (#24)
- bpmn-js 13.1.0 → 17.8.1
- Async error capture in diagram import (real errors surface in the UI now)
- Theme-aware loading panel (less flash on dark theme)

Release zip is built and waiting in GitHub draft. Once published, JetBrains Marketplace usually approves within ~2 business days. I'll comment again here when it's live.

Thanks for your patience and the sample files — they made the bug reproducible.
